spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  bootstrap-servers: localhost:9092
  poll:
    timeout: 1000
  topics:
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1