syntax = "proto3";

import "google/protobuf/empty.proto";
import "telemetry/messages/hub_event.proto";
import "telemetry/messages/sensor_event.proto";

package telemetry.services;

option java_multiple_files = true;
option java_package = "ru.yandex.practicum.grpc.telemetry.services";

service CollectorController {
  rpc CollectSensorEvent (telemetry.messages.SensorEventProto) returns (google.protobuf.Empty);
  rpc CollectHubEvent (telemetry.messages.HubEventProto) returns (google.protobuf.Empty);
}