spring:
  main:
    banner-mode: off
    log-startup-info: false

logging:
  level:
    ru.yandex.practicum: INFO
    org:
      springframework: WARN
      apache.kafka: WARN
      hibernate: WARN

kafka:
  bootstrap-servers: "localhost:9092"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30